'''
Feature: Authentication
Functionalities:
 - get_reset_password_link()
'''
from firebase_admin import auth
from .error import *

def get_reset_password_link(uid):
    '''
    Gets the link to reset password
    Args:
        - uid (string): User requesting to get link
    Returns:
        - link: Reset password link generated by API
    '''
    try:
        email = auth.get_user(uid).email
    except auth.UserNotFoundError:
        return -1
    else:
        return auth.generate_password_reset_link(email, {})
